sudo: required

services:
  - docker

script:
  - docker build -t rakshans1/cordova .
  - docker run rakshans1/cordova /bin/sh -c "cordova create test && cd test && cordova platform add android && cordova build android"
